### ISSUE TITLE
 ERR_PNPM_UNSUPPORTED_ENGINE when specified version is installed

### ISSUE THREAD

**Issue by jnimety** [privatenumber/ci#13]
When I specify a pnpm version in package.json that is older than the latest version of pnpm I get the ERR_PNPM_UNSUPPORTED_ENGINE error.

```
deploy@cherry:/var/www/redacted/beta/current$ pnpm --version
8.6.2
```

relevant package.json fields:
```
  "engines": {
    "node": "16 || 18",
    "pnpm": "8.6.2"
  },
  "packageManager": "pnpm@8.6.2"
```

```
deploy@cherry:/var/www/redacted/beta/current$ npx ci
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/var/www/redacted/beta/releases/20230712150540".

Expected version: 8.6.2
Got: 8.6.7

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```

**Comment by privatenumber** [comment]
This tool doesn't read the `packageManager ` property, but PR welcome to add support.

**Comment by jnimety** [comment]
I was more curious why pnpm is trying to use 8.6.7 when I only have 8.6.2 installed.

**Comment by jnimety** [comment]
ahhh, I see... `getPnpmVersion` returns "latest". Would you be opposed to removing the pnpm version specification for all together so it behaves like your yarn code path?  In other words, let pnpm decide what version to use.

**Comment by jnimety** [comment]
arguably it's less surprising to use an already installed version than to arbitrarily choose "latest", or 6, or 5 based on the version of node installed (and to let pnpm error out if there is a version conflict). However, this is your project and if you think it's appropriate to always force "latest" for new node versions I may have time to attempt a PR.

**Comment by privatenumber** [comment]
I think you're looking at it the wrong way.

The latest version isn't being "forced", it's simply the default version that gets installed when you don't specify a version. For example, when you do `npm install express`, it gets the latest version of express by default.

The difference here is that `npx ci` currently doesn't support a way to pass in a specific version. Which is why I said I welcome a PR to read the `packageManager` property.
