### ISSUE TITLE
[Feature] Relay any options passed to `ci` to the underlying command

### ISSUE THREAD

**Issue by ElMassimo** [privatenumber/ci#2]
First of all, thanks for sharing this library, incredibly useful to support all package managers without having to duplicate lock detection on every single project. And congrats on getting that package name 😄 

### Description 📖 

It would be useful if `ci` relayed any additional args to the resolved command.

In particular, I'm interested in passing `--prod=false` in certain situations where `NODE_ENV=production`, such as when a server needs to perform a build (and thus needs `devDependencies`).

Let me know if you would be interested in accepting a PR for this.

**Comment by privatenumber** [comment]
Looks like it's possible to achieve this via `NODE_ENV=development npx ci`. Does that work for you?

**Comment by ElMassimo** [comment]
Yes, that's the workaround I'm currently using.

Some post-install scripts could depend on `NODE_ENV`, so I was interested in finding a solution that does not modify `NODE_ENV`. Perhaps I'm over-thinking about it 😃

**Comment by privatenumber** [comment]
Gotcha, makes sense.

Seems like pnpm has a [`production` flag](https://pnpm.js.org/en/3.2/pnpm-install#production-true-false).

I couldn't find a yarn flag though. Looks like they have a [`--production` flag for `yarn workspaces focus`](https://yarnpkg.com/cli/workspaces/focus) but I'm not sure if that's what we want.


PR welcome if it's supported by all package managers!

**Comment by ElMassimo** [comment]
Yarn used to support it as well, but it seems that it's being [renamed in Yarn 2](https://yarnpkg.com/getting-started/migration/#cli-commands).

With the introduction of workspaces, it might require specific code to handle the differences between package managers. My original intention was that this library could just pass the options without checking them, but seems like that won't be possible with Yarn 2.

I'll think about it and revisit it if I come up with a good way to manage it. Thanks for checking!

**Comment by SevenOutman** [comment]
Also needed here. It's quite a common case to add flags to `npm ci` in CI pipelines.

    npm ci --cache $NPM_CACHE_DIR --prefer-offline # make use of CI cache
    npm ci --unsafe-perm # get around prevented scripts
